/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Codemon */

#ifndef _Included_Codemon
#define _Included_Codemon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Codemon
 * Method:    parseCodemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Codemon_parseCodemon
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     Codemon
 * Method:    runTestCodemon
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Codemon_runTestCodemon
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     Codemon
 * Method:    runSelfCodemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Codemon_runSelfCodemon
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     Codemon
 * Method:    runPVPCodemon
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Codemon_runPVPCodemon
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     Codemon
 * Method:    getReport
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Codemon_getReport
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
